---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: locker-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1

fargateProfiles:
  - name: fp-locker
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
      - namespace: locker

